{ config, homeDirectory, ... }:

{
  programs.foot = {
    enable = true;

    settings = {
      cursor = {
        blink = "no";
        style = "block";
      };
      main = {
        # Font configuration
        font = "monospace:size=10";
        # Theme is auto-generated by noctalia-shell
        include = "~/.config/foot/themes/noctalia";
        # Window configuration
        pad = "4x4";
      };
      mouse = {
        hide-when-typing = "yes";
      };
      scrollback = {
        lines = 10000;
      };
    };
  };
}
