{ config, homeDirectory, ... }:

{
  programs.kitty = {
    enable = true;

    # Include noctalia theme - theme file is auto-generated by noctalia-shell
    extraConfig = ''
      include themes/noctalia.conf

      # Tab colors come from themes/noctalia.conf (included above)
      active_tab_font_style           bold
      inactive_tab_font_style         normal

      tab_activity_symbol             " ● "
      tab_title_template              "{fmt.fg.red}{bell_symbol}{activity_symbol}{fmt.fg.tab}{title[:30]}{title[30:] and '…'} [{index}]"
      active_tab_title_template       "{fmt.fg.red}{bell_symbol}{activity_symbol}{fmt.fg.tab}{title[:30]}{title[30:] and '…'} [{index}]"
    '';

    settings = {
      bold_font = "auto";
      bold_italic_font = "auto";
      cursor_blink_interval = 0;
      # Cursor configuration
      cursor_shape = "block";
      detect_urls = true;
      # Font configuration
      font_family = "monospace";
      font_size = 10;
      initial_window_height = 400;
      initial_window_width = 640;
      input_delay = 3;
      italic_font = "auto";
      open_url_with = "default";
      remember_window_size = true;
      # Performance tuning
      repaint_delay = 10;
      # Shell integration
      shell = "fish";
      sync_to_monitor = true;
      tab_bar_align = "left";
      # Tab bar configuration
      tab_bar_edge = "top";
      "tab_bar_margin_height" = "2.5 1.5";
      tab_bar_margin_width = 0;
      tab_bar_min_tabs = 2;
      tab_bar_style = "powerline";
      tab_powerline_style = "slanted";
      # Mouse configuration
      url_style = "curly";
      # Window configuration
      window_padding_width = 4;
    };
  };
}
