{ config, homeDirectory, ... }:

{
  programs.kitty = {
    enable = true;

    settings = {
      # Font configuration
      font_family = "monospace";
      bold_font = "auto";
      italic_font = "auto";
      bold_italic_font = "auto";
      font_size = 10;

      # Window configuration
      window_padding_width = 4;
      remember_window_size = true;
      initial_window_width = 640;
      initial_window_height = 400;

      # Tab bar configuration
      tab_bar_edge = "top";
      tab_bar_style = "powerline";
      tab_powerline_style = "slanted";
      tab_bar_align = "left";
      tab_bar_min_tabs = 2;
      tab_bar_margin_width = 0;
      "tab_bar_margin_height" = "2.5 1.5";

      # Cursor configuration
      cursor_shape = "block";
      cursor_blink_interval = 0;

      # Mouse configuration
      url_style = "curly";
      open_url_with = "default";
      detect_urls = true;

      # Performance tuning
      repaint_delay = 10;
      input_delay = 3;
      sync_to_monitor = true;

      # Shell integration
      shell = "fish";
    };

    # Include noctalia theme - theme file is auto-generated by noctalia-shell
    extraConfig = ''
      include themes/noctalia.conf

      # Tab colors will use theme colors
      tab_bar_background              background
      active_tab_foreground           background
      active_tab_background           color6
      active_tab_font_style           bold
      inactive_tab_foreground         foreground
      inactive_tab_background         background
      inactive_tab_font_style         normal

      tab_activity_symbol             " ● "
      tab_title_template              "{fmt.fg.red}{bell_symbol}{activity_symbol}{fmt.fg.tab}{title[:30]}{title[30:] and '…'} [{index}]"
      active_tab_title_template       "{fmt.fg.red}{bell_symbol}{activity_symbol}{fmt.fg.tab}{title[:30]}{title[30:] and '…'} [{index}]"
    '';
  };
}
