name: check

on:
  push:
    branches: [main]
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - name: Formatting
        run: nix fmt -- --check $(git ls-files '*.nix')
      - name: Flake check
        run: nix flake check
